# Generated by Django 4.1.4 on 2022-12-10 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Motor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carName', models.CharField(max_length=100)),
                ('carNumber', models.CharField(max_length=200)),
                ('registrationYear', models.CharField(max_length=10)),
                ('variantOfCar', models.CharField(max_length=200)),
            ],
        ),
    ]
