# Generated by Django 4.1.4 on 2022-12-10 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turtlemintapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotorInsurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bankName', models.CharField(max_length=100)),
                ('insuranceType', models.CharField(max_length=200)),
                ('premium', models.BigIntegerField(default=0)),
                ('yearly', models.BigIntegerField(default=1)),
                ('benefits1', models.SmallIntegerField(default=0)),
                ('benefits2', models.SmallIntegerField(default=0)),
                ('benefits3', models.SmallIntegerField(default=0)),
                ('benefits4', models.SmallIntegerField(default=0)),
                ('depriciationValue', models.BigIntegerField()),
                ('carId', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='turtlemintapp.motor')),
            ],
        ),
    ]
